// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AcceptanceCriteria.VerificaPT
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("WBC-1019 - Annullo Erogazione PT", Description="\t*IN ORDER TO* rendere nuovamente disponibile la qtà precedentemente erogata\r\n\t*A" +
        "S* Farmacia\r\n\t*I WANT TO* annullare un\'erogazione precedentemente eseguita", SourceFile="VerificaPT\\WBC-1019_AnnulloErogazione PT.feature", SourceLine=0)]
    public partial class WBC_1019_AnnulloErogazionePTFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "WBC-1019_AnnulloErogazione PT.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "WBC-1019 - Annullo Erogazione PT", "\t*IN ORDER TO* rendere nuovamente disponibile la qtà precedentemente erogata\r\n\t*A" +
                    "S* Farmacia\r\n\t*I WANT TO* annullare un\'erogazione precedentemente eseguita", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("1. Annullo Erogazione", SourceLine=5)]
        public virtual void _1_AnnulloErogazione()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("1. Annullo Erogazione", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "CodicePT",
                        "Confezioni",
                        "Minsan",
                        "DataRicetta",
                        "DataErogazione",
                        "NumeroRicetta",
                        "CodiceFarmacia",
                        "Annullato"});
            table1.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "2",
                        "036892053",
                        "2017-09-06",
                        "2017-09-07",
                        "120171000000001",
                        "1234",
                        "false"});
            table1.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "3",
                        "036892089",
                        "2017-09-10",
                        "2017-09-10",
                        "120172000000002",
                        "7890",
                        "false"});
#line 7
 testRunner.Given("risultano seguenti erogazioni di prodotti associate al PT = NH6F5J20K2C5TCPD", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "CodicePT",
                        "NumeroRicetta",
                        "CodiceFarmacia"});
            table2.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "120171000000001",
                        "1234"});
#line 11
 testRunner.When("ricevo il seguente annullo di erogazione prodotti", ((string)(null)), table2, "When ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Esito",
                        "Errori.Key",
                        "Errori.Value"});
            table3.AddRow(new string[] {
                        "true",
                        "",
                        ""});
#line 14
 testRunner.Then("viene restituito", ((string)(null)), table3, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "CodicePT",
                        "Confezioni",
                        "Minsan",
                        "DataRicetta",
                        "DataErogazione",
                        "NumeroRicetta",
                        "CodiceFarmacia",
                        "Annullato"});
            table4.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "2",
                        "036892053",
                        "2017-09-06",
                        "2017-09-07",
                        "120171000000001",
                        "1234",
                        "true"});
            table4.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "3",
                        "036892089",
                        "2017-09-10",
                        "2017-09-10",
                        "120172000000002",
                        "7890",
                        "false"});
#line 17
 testRunner.And("risultano seguenti erogazioni di prodotti associate al PT = NH6F5J20K2C5TCPD", ((string)(null)), table4, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("2. Annullo Erogazione con 2 prodotti diversi", SourceLine=21)]
        public virtual void _2_AnnulloErogazioneCon2ProdottiDiversi()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("2. Annullo Erogazione con 2 prodotti diversi", ((string[])(null)));
#line 22
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "CodicePT",
                        "Confezioni",
                        "Minsan",
                        "DataRicetta",
                        "DataErogazione",
                        "NumeroRicetta",
                        "CodiceFarmacia",
                        "Annullato"});
            table5.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "2",
                        "036892053",
                        "2017-09-06",
                        "2017-09-07",
                        "120171000000001",
                        "1234",
                        "false"});
            table5.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "3",
                        "036892089",
                        "2017-09-10",
                        "2017-09-10",
                        "120172000000002",
                        "7890",
                        "false"});
            table5.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "1",
                        "036892089",
                        "2017-09-06",
                        "2017-09-07",
                        "120171000000001",
                        "1234",
                        "false"});
#line 23
 testRunner.Given("risultano seguenti erogazioni di prodotti associate al PT = NH6F5J20K2C5TCPD", ((string)(null)), table5, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "CodicePT",
                        "NumeroRicetta",
                        "CodiceFarmacia"});
            table6.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "120171000000001",
                        "1234"});
#line 28
 testRunner.When("ricevo il seguente annullo di erogazione prodotti", ((string)(null)), table6, "When ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Esito",
                        "Errori.Key",
                        "Errori.Value"});
            table7.AddRow(new string[] {
                        "true",
                        "",
                        ""});
#line 31
 testRunner.Then("viene restituito", ((string)(null)), table7, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "CodicePT",
                        "Confezioni",
                        "Minsan",
                        "DataRicetta",
                        "DataErogazione",
                        "NumeroRicetta",
                        "CodiceFarmacia",
                        "Annullato"});
            table8.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "2",
                        "036892053",
                        "2017-09-06",
                        "2017-09-07",
                        "120171000000001",
                        "1234",
                        "true"});
            table8.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "3",
                        "036892089",
                        "2017-09-10",
                        "2017-09-10",
                        "120172000000002",
                        "7890",
                        "false"});
            table8.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "1",
                        "036892089",
                        "2017-09-06",
                        "2017-09-07",
                        "120171000000001",
                        "1234",
                        "true"});
#line 34
 testRunner.And("risultano seguenti erogazioni di prodotti associate al PT = NH6F5J20K2C5TCPD", ((string)(null)), table8, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("3. Annullo senza trovare corrispondenza della ricetta", SourceLine=39)]
        public virtual void _3_AnnulloSenzaTrovareCorrispondenzaDellaRicetta()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("3. Annullo senza trovare corrispondenza della ricetta", ((string[])(null)));
#line 40
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "CodicePT",
                        "Confezioni",
                        "Minsan",
                        "DataRicetta",
                        "DataErogazione",
                        "NumeroRicetta",
                        "CodiceFarmacia",
                        "Annullato"});
            table9.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "2",
                        "036892053",
                        "2017-09-06",
                        "2017-09-07",
                        "120171000000001",
                        "1234",
                        "false"});
            table9.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "3",
                        "036892089",
                        "2017-09-10",
                        "2017-09-10",
                        "120172000000002",
                        "7890",
                        "false"});
#line 41
 testRunner.Given("risultano seguenti erogazioni di prodotti associate al PT = NH6F5J20K2C5TCPD", ((string)(null)), table9, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "CodicePT",
                        "NumeroRicetta",
                        "CodiceFarmacia"});
            table10.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "120171000000012",
                        "1234"});
#line 45
 testRunner.When("ricevo il seguente annullo di erogazione prodotti", ((string)(null)), table10, "When ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Esito",
                        "Errori.Key",
                        "Errori.Value"});
            table11.AddRow(new string[] {
                        "false",
                        "16",
                        "IMPOSSIBILE_RIPRISTINARE_QTA"});
#line 48
 testRunner.Then("viene restituito", ((string)(null)), table11, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "CodicePT",
                        "Confezioni",
                        "Minsan",
                        "DataRicetta",
                        "DataErogazione",
                        "NumeroRicetta",
                        "CodiceFarmacia",
                        "Annullato"});
            table12.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "2",
                        "036892053",
                        "2017-09-06",
                        "2017-09-07",
                        "120171000000001",
                        "1234",
                        "false"});
            table12.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "3",
                        "036892089",
                        "2017-09-10",
                        "2017-09-10",
                        "120172000000002",
                        "7890",
                        "false"});
#line 51
 testRunner.And("risultano seguenti erogazioni di prodotti associate al PT = NH6F5J20K2C5TCPD", ((string)(null)), table12, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("4. Annullo senza trovare corrispondenza della farmacia", SourceLine=55)]
        public virtual void _4_AnnulloSenzaTrovareCorrispondenzaDellaFarmacia()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("4. Annullo senza trovare corrispondenza della farmacia", ((string[])(null)));
#line 56
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "CodicePT",
                        "Confezioni",
                        "Minsan",
                        "DataRicetta",
                        "DataErogazione",
                        "NumeroRicetta",
                        "CodiceFarmacia",
                        "Annullato"});
            table13.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "2",
                        "036892053",
                        "2017-09-06",
                        "2017-09-07",
                        "120171000000001",
                        "1234",
                        "false"});
            table13.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "3",
                        "036892089",
                        "2017-09-10",
                        "2017-09-10",
                        "120172000000002",
                        "7890",
                        "false"});
#line 57
 testRunner.Given("risultano seguenti erogazioni di prodotti associate al PT = NH6F5J20K2C5TCPD", ((string)(null)), table13, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "CodicePT",
                        "NumeroRicetta",
                        "CodiceFarmacia"});
            table14.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "120171000000001",
                        "1235"});
#line 61
 testRunner.When("ricevo il seguente annullo di erogazione prodotti", ((string)(null)), table14, "When ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Esito",
                        "Errori.Key",
                        "Errori.Value"});
            table15.AddRow(new string[] {
                        "false",
                        "16",
                        "IMPOSSIBILE_RIPRISTINARE_QTA"});
#line 64
 testRunner.Then("viene restituito", ((string)(null)), table15, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "CodicePT",
                        "Confezioni",
                        "Minsan",
                        "DataRicetta",
                        "DataErogazione",
                        "NumeroRicetta",
                        "CodiceFarmacia",
                        "Annullato"});
            table16.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "2",
                        "036892053",
                        "2017-09-06",
                        "2017-09-07",
                        "120171000000001",
                        "1234",
                        "false"});
            table16.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "3",
                        "036892089",
                        "2017-09-10",
                        "2017-09-10",
                        "120172000000002",
                        "7890",
                        "false"});
#line 67
 testRunner.And("risultano seguenti erogazioni di prodotti associate al PT = NH6F5J20K2C5TCPD", ((string)(null)), table16, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("5. Annullo di erogazione già annullata", SourceLine=71)]
        public virtual void _5_AnnulloDiErogazioneGiaAnnullata()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5. Annullo di erogazione già annullata", ((string[])(null)));
#line 72
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "CodicePT",
                        "Confezioni",
                        "Minsan",
                        "DataRicetta",
                        "DataErogazione",
                        "NumeroRicetta",
                        "CodiceFarmacia",
                        "Annullato"});
            table17.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "2",
                        "036892053",
                        "2017-09-06",
                        "2017-09-07",
                        "120171000000001",
                        "1234",
                        "true"});
            table17.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "3",
                        "036892089",
                        "2017-09-10",
                        "2017-09-10",
                        "120172000000002",
                        "7890",
                        "false"});
#line 73
 testRunner.Given("risultano seguenti erogazioni di prodotti associate al PT = NH6F5J20K2C5TCPD", ((string)(null)), table17, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "CodicePT",
                        "NumeroRicetta",
                        "CodiceFarmacia"});
            table18.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "120171000000001",
                        "1234"});
#line 77
 testRunner.When("ricevo il seguente annullo di erogazione prodotti", ((string)(null)), table18, "When ");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "Esito",
                        "Errori.Key",
                        "Errori.Value"});
            table19.AddRow(new string[] {
                        "false",
                        "16",
                        "IMPOSSIBILE_RIPRISTINARE_QTA"});
#line 80
 testRunner.Then("viene restituito", ((string)(null)), table19, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "CodicePT",
                        "Confezioni",
                        "Minsan",
                        "DataRicetta",
                        "DataErogazione",
                        "NumeroRicetta",
                        "CodiceFarmacia",
                        "Annullato"});
            table20.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "2",
                        "036892053",
                        "2017-09-06",
                        "2017-09-07",
                        "120171000000001",
                        "1234",
                        "true"});
            table20.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "3",
                        "036892089",
                        "2017-09-10",
                        "2017-09-10",
                        "120172000000002",
                        "7890",
                        "false"});
#line 83
 testRunner.And("risultano seguenti erogazioni di prodotti associate al PT = NH6F5J20K2C5TCPD", ((string)(null)), table20, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("6. Annullo di erogazione non presente", SourceLine=87)]
        public virtual void _6_AnnulloDiErogazioneNonPresente()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("6. Annullo di erogazione non presente", ((string[])(null)));
#line 88
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "CodicePT",
                        "Confezioni",
                        "Minsan",
                        "DataRicetta",
                        "DataErogazione",
                        "NumeroRicetta",
                        "CodiceFarmacia",
                        "Annullato"});
#line 89
 testRunner.Given("risultano seguenti erogazioni di prodotti associate al PT = NH6F5J20K2C5TCPD", ((string)(null)), table21, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "CodicePT",
                        "NumeroRicetta",
                        "CodiceFarmacia"});
            table22.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "120171000000001",
                        "1234"});
#line 91
 testRunner.When("ricevo il seguente annullo di erogazione prodotti", ((string)(null)), table22, "When ");
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "Esito",
                        "Errori.Key",
                        "Errori.Value"});
            table23.AddRow(new string[] {
                        "false",
                        "16",
                        "IMPOSSIBILE_RIPRISTINARE_QTA"});
#line 94
 testRunner.Then("viene restituito", ((string)(null)), table23, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "CodicePT",
                        "Confezioni",
                        "Minsan",
                        "DataRicetta",
                        "DataErogazione",
                        "NumeroRicetta",
                        "CodiceFarmacia",
                        "Annullato"});
#line 97
 testRunner.And("risultano seguenti erogazioni di prodotti associate al PT = NH6F5J20K2C5TCPD", ((string)(null)), table24, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("7. Annullo di erogazione in presenza di erogazione senza riferimento ricetta", SourceLine=99)]
        public virtual void _7_AnnulloDiErogazioneInPresenzaDiErogazioneSenzaRiferimentoRicetta()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("7. Annullo di erogazione in presenza di erogazione senza riferimento ricetta", ((string[])(null)));
#line 100
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "CodicePT",
                        "Confezioni",
                        "Minsan",
                        "DataRicetta",
                        "DataErogazione",
                        "NumeroRicetta",
                        "CodiceFarmacia",
                        "Annullato"});
            table25.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "2",
                        "036892053",
                        "2017-09-06",
                        "2017-09-07",
                        "",
                        "",
                        "false"});
            table25.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "3",
                        "036892089",
                        "2017-09-10",
                        "2017-09-10",
                        "120172000000002",
                        "7890",
                        "false"});
#line 101
 testRunner.Given("risultano seguenti erogazioni di prodotti associate al PT = NH6F5J20K2C5TCPD", ((string)(null)), table25, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "CodicePT",
                        "NumeroRicetta",
                        "CodiceFarmacia"});
            table26.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "120171000000001",
                        "1234"});
#line 105
 testRunner.When("ricevo il seguente annullo di erogazione prodotti", ((string)(null)), table26, "When ");
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "Esito",
                        "Errori.Key",
                        "Errori.Value"});
            table27.AddRow(new string[] {
                        "false",
                        "16",
                        "IMPOSSIBILE_RIPRISTINARE_QTA"});
#line 108
 testRunner.Then("viene restituito", ((string)(null)), table27, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                        "CodicePT",
                        "Confezioni",
                        "Minsan",
                        "DataRicetta",
                        "DataErogazione",
                        "NumeroRicetta",
                        "CodiceFarmacia",
                        "Annullato"});
            table28.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "2",
                        "036892053",
                        "2017-09-06",
                        "2017-09-07",
                        "",
                        "",
                        "false"});
            table28.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "3",
                        "036892089",
                        "2017-09-10",
                        "2017-09-10",
                        "120172000000002",
                        "7890",
                        "false"});
#line 111
 testRunner.And("risultano seguenti erogazioni di prodotti associate al PT = NH6F5J20K2C5TCPD", ((string)(null)), table28, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("8. Annullo Erogazione con ricetta presente in 2 farmacie", SourceLine=116)]
        public virtual void _8_AnnulloErogazioneConRicettaPresenteIn2Farmacie()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("8. Annullo Erogazione con ricetta presente in 2 farmacie", ((string[])(null)));
#line 117
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                        "CodicePT",
                        "Confezioni",
                        "Minsan",
                        "DataRicetta",
                        "DataErogazione",
                        "NumeroRicetta",
                        "CodiceFarmacia",
                        "Annullato"});
            table29.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "2",
                        "036892053",
                        "2017-09-06",
                        "2017-09-07",
                        "120171000000001",
                        "1234",
                        "false"});
            table29.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "3",
                        "036892089",
                        "2017-09-10",
                        "2017-09-10",
                        "120172000000002",
                        "7890",
                        "false"});
            table29.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "3",
                        "036892089",
                        "2017-09-10",
                        "2017-09-10",
                        "120172000000002",
                        "7777",
                        "false"});
            table29.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "1",
                        "036892089",
                        "2017-09-06",
                        "2017-09-07",
                        "120171000000001",
                        "1234",
                        "false"});
#line 118
 testRunner.Given("risultano seguenti erogazioni di prodotti associate al PT = NH6F5J20K2C5TCPD", ((string)(null)), table29, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                        "CodicePT",
                        "NumeroRicetta",
                        "CodiceFarmacia"});
            table30.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "120172000000002",
                        "7777"});
#line 124
 testRunner.When("ricevo il seguente annullo di erogazione prodotti", ((string)(null)), table30, "When ");
#line hidden
            TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                        "Esito",
                        "Errori.Key",
                        "Errori.Value"});
            table31.AddRow(new string[] {
                        "true",
                        "",
                        ""});
#line 127
 testRunner.Then("viene restituito", ((string)(null)), table31, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                        "CodicePT",
                        "Confezioni",
                        "Minsan",
                        "DataRicetta",
                        "DataErogazione",
                        "NumeroRicetta",
                        "CodiceFarmacia",
                        "Annullato"});
            table32.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "2",
                        "036892053",
                        "2017-09-06",
                        "2017-09-07",
                        "120171000000001",
                        "1234",
                        "false"});
            table32.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "3",
                        "036892089",
                        "2017-09-10",
                        "2017-09-10",
                        "120172000000002",
                        "7890",
                        "false"});
            table32.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "3",
                        "036892089",
                        "2017-09-10",
                        "2017-09-10",
                        "120172000000002",
                        "7777",
                        "true"});
            table32.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "1",
                        "036892089",
                        "2017-09-06",
                        "2017-09-07",
                        "120171000000001",
                        "1234",
                        "false"});
#line 130
 testRunner.And("risultano seguenti erogazioni di prodotti associate al PT = NH6F5J20K2C5TCPD", ((string)(null)), table32, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("9. Annullo di erogazione in presenza di erogazione senza riferimento farmacia. (P" +
            "ARLIAMONE!!!!!)", SourceLine=137)]
        public virtual void _9_AnnulloDiErogazioneInPresenzaDiErogazioneSenzaRiferimentoFarmacia_PARLIAMONE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("9. Annullo di erogazione in presenza di erogazione senza riferimento farmacia. (P" +
                    "ARLIAMONE!!!!!)", ((string[])(null)));
#line 138
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table33 = new TechTalk.SpecFlow.Table(new string[] {
                        "CodicePT",
                        "Confezioni",
                        "Minsan",
                        "DataRicetta",
                        "DataErogazione",
                        "NumeroRicetta",
                        "CodiceFarmacia",
                        "Annullato"});
            table33.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "2",
                        "036892053",
                        "2017-09-06",
                        "2017-09-07",
                        "120171000000001",
                        "",
                        "false"});
            table33.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "3",
                        "036892089",
                        "2017-09-10",
                        "2017-09-10",
                        "120172000000002",
                        "7890",
                        "false"});
#line 139
 testRunner.Given("risultano seguenti erogazioni di prodotti associate al PT = NH6F5J20K2C5TCPD", ((string)(null)), table33, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table34 = new TechTalk.SpecFlow.Table(new string[] {
                        "CodicePT",
                        "NumeroRicetta",
                        "CodiceFarmacia"});
            table34.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "120171000000001",
                        "1234"});
#line 143
 testRunner.When("ricevo il seguente annullo di erogazione prodotti", ((string)(null)), table34, "When ");
#line hidden
            TechTalk.SpecFlow.Table table35 = new TechTalk.SpecFlow.Table(new string[] {
                        "Esito",
                        "Errori.Key",
                        "Errori.Value"});
            table35.AddRow(new string[] {
                        "false",
                        "16",
                        "IMPOSSIBILE_RIPRISTINARE_QTA"});
#line 146
 testRunner.Then("viene restituito", ((string)(null)), table35, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table36 = new TechTalk.SpecFlow.Table(new string[] {
                        "CodicePT",
                        "Confezioni",
                        "Minsan",
                        "DataRicetta",
                        "DataErogazione",
                        "NumeroRicetta",
                        "CodiceFarmacia",
                        "Annullato"});
            table36.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "2",
                        "036892053",
                        "2017-09-06",
                        "2017-09-07",
                        "120171000000001",
                        "",
                        "false"});
            table36.AddRow(new string[] {
                        "NH6F5J20K2C5TCPD",
                        "3",
                        "036892089",
                        "2017-09-10",
                        "2017-09-10",
                        "120172000000002",
                        "7890",
                        "false"});
#line 149
 testRunner.And("risultano seguenti erogazioni di prodotti associate al PT = NH6F5J20K2C5TCPD", ((string)(null)), table36, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
