// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AcceptanceCriteria.VerificaPT
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("WBC-994_Anonimizzazione_Dati_Paziente", Description="\tIN ORDER TO aderire alle nuove norme sulla privacy\r\n\tAS Studiofarma\r\n\tI WANT TO " +
        "salvare un guid al posto del codice fiscale", SourceFile="VerificaPT\\WBC-994_Anonimizzazione_Dati_Paziente.feature", SourceLine=0)]
    public partial class WBC_994_Anonimizzazione_Dati_PazienteFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "WBC-994_Anonimizzazione_Dati_Paziente.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "WBC-994_Anonimizzazione_Dati_Paziente", "\tIN ORDER TO aderire alle nuove norme sulla privacy\r\n\tAS Studiofarma\r\n\tI WANT TO " +
                    "salvare un guid al posto del codice fiscale", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Restituzione Scheda Assistito passando il Codice Fiscale", new string[] {
                "mytag"}, SourceLine=6)]
        public virtual void RestituzioneSchedaAssistitoPassandoIlCodiceFiscale()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Restituzione Scheda Assistito passando il Codice Fiscale", new string[] {
                        "mytag"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "GUIDAssistito",
                        "Codice Fiscale",
                        "Nome",
                        "Cognome",
                        "Data Nascita",
                        "Luogo Nascita",
                        "Sesso",
                        "Indirizzo",
                        "Comune",
                        "Cap",
                        "Provincia",
                        "Telefono",
                        "Regione",
                        "ASL"});
            table1.AddRow(new string[] {
                        "7a2c3353-12b6-47b1-b566-3f2779f6fc9d",
                        "MDCDGI70B12E704B",
                        "Diego",
                        "Medici",
                        "12-02-1970",
                        "Lovere (BG)",
                        "M",
                        "Via Presolana, 6",
                        "Rogno",
                        "24060",
                        "BG",
                        "555-345-665",
                        "Lombardia",
                        "ATS Bergamo"});
#line 8
 testRunner.Given("la seguente scheda assistito su WebCare", ((string)(null)), table1, "Given ");
#line 11
 testRunner.When("da PTOnline chiamo il servizio di interrogazione degli assistiti passando il Codi" +
                    "ceFiscale=\"MDCDGI70B12E704B\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "GUIDAssistito",
                        "Codice Fiscale",
                        "Nome",
                        "Cognome",
                        "Data Nascita",
                        "Luogo Nascita",
                        "Sesso",
                        "Indirizzo",
                        "Comune",
                        "Cap",
                        "Provincia",
                        "Telefono",
                        "Regione",
                        "ASL"});
            table2.AddRow(new string[] {
                        "7a2c3353-12b6-47b1-b566-3f2779f6fc9d",
                        "MDCDGI70B12E704B",
                        "Diego",
                        "Medici",
                        "12-02-1970",
                        "Lovere (BG)",
                        "M",
                        "Via Presolana, 6",
                        "Rogno",
                        "24060",
                        "BG",
                        "555-345-665",
                        "Lombardia",
                        "ATS Bergamo"});
#line 12
 testRunner.Then("il servizio di interrogazione degli assistiti restituisce", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Restituzione Scheda Assistito passando il GuidAssistito", SourceLine=15)]
        public virtual void RestituzioneSchedaAssistitoPassandoIlGuidAssistito()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Restituzione Scheda Assistito passando il GuidAssistito", ((string[])(null)));
#line 16
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "GUIDAssistito",
                        "Codice Fiscale",
                        "Nome",
                        "Cognome",
                        "Data Nascita",
                        "Luogo Nascita",
                        "Sesso",
                        "Indirizzo",
                        "Comune",
                        "Cap",
                        "Provincia",
                        "Telefono",
                        "Regione",
                        "ASL"});
            table3.AddRow(new string[] {
                        "7a2c3353-12b6-47b1-b566-3f2779f6fc9d",
                        "MDCDGI70B12E704B",
                        "Diego",
                        "Medici",
                        "12-02-1970",
                        "Lovere (BG)",
                        "M",
                        "Via Presolana, 6",
                        "Rogno",
                        "24060",
                        "BG",
                        "555-345-665",
                        "Lombardia",
                        "ATS Bergamo"});
#line 17
 testRunner.Given("la seguente scheda assistito su WebCare", ((string)(null)), table3, "Given ");
#line 20
 testRunner.When("da PTOnline chiamo il servizio di interrogazione degli assistiti passando il Guid" +
                    "Assistito=\"7a2c3353-12b6-47b1-b566-3f2779f6fc9d\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "GUIDAssistito",
                        "Codice Fiscale",
                        "Nome",
                        "Cognome",
                        "Data Nascita",
                        "Luogo Nascita",
                        "Sesso",
                        "Indirizzo",
                        "Comune",
                        "Cap",
                        "Provincia",
                        "Telefono",
                        "Regione",
                        "ASL"});
            table4.AddRow(new string[] {
                        "7a2c3353-12b6-47b1-b566-3f2779f6fc9d",
                        "MDCDGI70B12E704B",
                        "Diego",
                        "Medici",
                        "12-02-1970",
                        "Lovere (BG)",
                        "M",
                        "Via Presolana, 6",
                        "Rogno",
                        "24060",
                        "BG",
                        "555-345-665",
                        "Lombardia",
                        "ATS Bergamo"});
#line 21
 testRunner.Then("il servizio di interrogazione degli assistiti restituisce", ((string)(null)), table4, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Restituzione Scheda Assistito passando il Codice Fiscale e creazione GuidAssistit" +
            "o", SourceLine=24)]
        public virtual void RestituzioneSchedaAssistitoPassandoIlCodiceFiscaleECreazioneGuidAssistito()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Restituzione Scheda Assistito passando il Codice Fiscale e creazione GuidAssistit" +
                    "o", ((string[])(null)));
#line 25
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "GUIDAssistito",
                        "Codice Fiscale",
                        "Nome",
                        "Cognome",
                        "Data Nascita",
                        "Luogo Nascita",
                        "Sesso",
                        "Indirizzo",
                        "Comune",
                        "Cap",
                        "Provincia",
                        "Telefono",
                        "Regione",
                        "ASL"});
            table5.AddRow(new string[] {
                        "null",
                        "MDCDGI70B12E704B",
                        "Diego",
                        "Medici",
                        "12-02-1970",
                        "Lovere (BG)",
                        "M",
                        "Via Presolana, 6",
                        "Rogno",
                        "24060",
                        "BG",
                        "555-345-665",
                        "Lombardia",
                        "ATS Bergamo"});
#line 26
 testRunner.Given("la seguente scheda assistito su WebCare", ((string)(null)), table5, "Given ");
#line 29
 testRunner.When("da PTOnline chiamo il servizio di interrogazione degli assistiti passando il Codi" +
                    "ceFiscale=\"MDCDGI70B12E704B\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 30
 testRunner.Then("WebCare crea il nuovo GuidAssistito=\"7a2c3353-12b6-47b1-b566-3f2779f6fc9d\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 31
 testRunner.And("lo associa all\'assistito \"MDCDGI70B12E704B\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "GUIDAssistito",
                        "Codice Fiscale",
                        "Nome",
                        "Cognome",
                        "Data Nascita",
                        "Luogo Nascita",
                        "Sesso",
                        "Indirizzo",
                        "Comune",
                        "Cap",
                        "Provincia",
                        "Telefono",
                        "Regione",
                        "ASL"});
            table6.AddRow(new string[] {
                        "7a2c3353-12b6-47b1-b566-3f2779f6fc9d",
                        "MDCDGI70B12E704B",
                        "Diego",
                        "Medici",
                        "12-02-1970",
                        "Lovere (BG)",
                        "M",
                        "Via Presolana, 6",
                        "Rogno",
                        "24060",
                        "BG",
                        "555-345-665",
                        "Lombardia",
                        "ATS Bergamo"});
#line 32
 testRunner.And("salva la seguente scheda assistito", ((string)(null)), table6, "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "GUIDAssistito",
                        "Codice Fiscale",
                        "Nome",
                        "Cognome",
                        "Data Nascita",
                        "Luogo Nascita",
                        "Sesso",
                        "Indirizzo",
                        "Comune",
                        "Cap",
                        "Provincia",
                        "Telefono",
                        "Regione",
                        "ASL"});
            table7.AddRow(new string[] {
                        "7a2c3353-12b6-47b1-b566-3f2779f6fc9d",
                        "MDCDGI70B12E704B",
                        "Diego",
                        "Medici",
                        "12-02-1970",
                        "Lovere (BG)",
                        "M",
                        "Via Presolana, 6",
                        "Rogno",
                        "24060",
                        "BG",
                        "555-345-665",
                        "Lombardia",
                        "ATS Bergamo"});
#line 35
 testRunner.And("il servizio di interrogazione degli assistiti restituisce", ((string)(null)), table7, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("CodiceFiscale Assistito non presente", SourceLine=38)]
        public virtual void CodiceFiscaleAssistitoNonPresente()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("CodiceFiscale Assistito non presente", ((string[])(null)));
#line 39
this.ScenarioSetup(scenarioInfo);
#line 40
 testRunner.Given("non è presente sulla scheda assistito su WebCare il CodiceFiscale=\"MDCDGI70B12E70" +
                    "4B\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 41
 testRunner.When("da PTOnline chiamo il servizio di interrogazione degli assistiti passando il Codi" +
                    "ceFiscale=\"MDCDGI70B12E704B\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 42
 testRunner.Then("il servizio di interrogazione degli assistiti restituisce l\'errore \"Assistito non" +
                    " Censito\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("GuidAssistito Assistito non presente", SourceLine=43)]
        public virtual void GuidAssistitoAssistitoNonPresente()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GuidAssistito Assistito non presente", ((string[])(null)));
#line 44
this.ScenarioSetup(scenarioInfo);
#line 45
 testRunner.Given("non è presente sulla scheda assistito su WebCare il GUIDAssistito=\"7a2c3353-12b6-" +
                    "47b1-b566-3f2779f6fc9d\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 46
 testRunner.When("da PTOnline chiamo il servizio di interrogazione degli assistiti passando il Guid" +
                    "Assistito=\"7a2c3353-12b6-47b1-b566-3f2779f6fc9d\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 47
 testRunner.Then("il servizio di interrogazione degli assistiti restituisce l\'errore \"Assistito non" +
                    " Censito\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
